const inventory_chilean = [
    {
        "YEAR EDIT": 1,
        "YEAR DATE": 1991,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 1,
        "COVER": "SUPER MARIO WORLD",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 1,
        "YEAR DATE": 1992,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 2,
        "COVER": "SUPER MARIO BROS. 3",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 1,
        "YEAR DATE": 1992,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 3,
        "COVER": "BART - LOS SIMPSONS",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 1,
        "YEAR DATE": 1992,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 4,
        "COVER": "F-ZERO",
        "OWNED": "NO",
        "POSTER THEME": "DOUBLE DRAGON III"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 5,
        "COVER": "TINY TOONS",
        "OWNED": "NO",
        "POSTER THEME": "EXTRA: CUBITIPS SUPER MARIO BROS. 3"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 6,
        "COVER": "THE FLINSTONES - PICAPIEDRAS",
        "OWNED": "NO",
        "POSTER THEME": "EXTRA: CUBITIPS BATMAN RETURN OF THE JOKER"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 7,
        "COVER": "STREET FIGHTER II",
        "OWNED": "NO",
        "POSTER THEME": "STREET FIGHTER II / EXTRA: CUBITIPS SUPER MARIO WORLD"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 8,
        "COVER": "MARIO PAINT",
        "OWNED": "NO",
        "POSTER THEME": "FELIX THE CAT / AXELAY"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 9,
        "COVER": "DEATH VALLEY RALLY - COYOTE - CORRECAMINOS",
        "OWNED": "NO",
        "POSTER THEME": "CONTRA / SUPER MARIO KART"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 10,
        "COVER": "STARFOX",
        "OWNED": "NO",
        "POSTER THEME": "TMNT TURTLES IN TIME"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 11,
        "COVER": "BATMAN",
        "OWNED": "NO",
        "POSTER THEME": "ADVENTURE ISLAND 3"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 12,
        "COVER": "TINY TOONS",
        "OWNED": "NO",
        "POSTER THEME": "BATMAN RETURNS / CONTRA III"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 13,
        "COVER": "PRINCE OF PERSIA",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 14,
        "COVER": "MORTAL KOMBAT",
        "OWNED": "NO",
        "POSTER THEME": "CYBERNATOR"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 15,
        "COVER": "STREET FIGHTER II TURBO",
        "OWNED": "NO",
        "POSTER THEME": "CALENDARIO 1994 / STARFOX"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 16,
        "COVER": "BATTLETOADS",
        "OWNED": "NO",
        "POSTER THEME": "RUN SABER"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 17,
        "COVER": "FINAL FIGHT 2",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 18,
        "COVER": "MEGAMAN X",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 19,
        "COVER": "METROID",
        "OWNED": "NO",
        "POSTER THEME": "MEGAMAN X"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 20,
        "COVER": "NBA JAM",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 21,
        "COVER": "JURASSIC PARK",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 22,
        "COVER": "MEGA MAN SOCCER",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 23,
        "COVER": "STUNT RACE FX",
        "OWNED": "NO",
        "POSTER THEME": "STREET FIGHTER II TURBO / KING OF FIGHTERS"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 24,
        "COVER": "SUPER METROID",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 29-36",
        "POSTER THEME": "SPEEDY GONZALES LOS GATOS BANDIDOS / SUPER METROID",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 25,
        "COVER": "ALIEN VS. PREDATOR - STUNT RACE FX - ITCHY & SCRATCHY",
        "OWNED": "NO",
        "POSTER THEME": "ALIEN VS. PREDATOR - STUNT RACE FX - ITCHY & SCRATCHY"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 26,
        "COVER": "SUPER BOMBERMAN 2 - SUPER ADVENTURE ISLAND 2 - DONKEY KONG COUNTRY",
        "OWNED": "YES-POOR",
        "POSTER": "MISSING: PAGES 29-36",
        "POSTER THEME": "SUPER BOMBERMAN 2 - SUPER ADVENTURE ISLAND 2 - DONKEY KONG COUNTRY / LETHAL ENFORCERS",
        "OBSERVATION": "PÁGINA CENTRAL SUELTA",
        "COUNTRY": "ARGENTINA"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 27,
        "COVER": "DONKEY KONG COUNTRY",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 31-34",
        "POSTER THEME": "DONKEY KONG COUNTRY / DARKSTALKERS",
        "COUNTRY": "ARGENTINA"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 28,
        "COVER": "MORTAL KOMBAT II",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 29-36",
        "POSTER THEME": "CALENDARIO 1995",
        "COUNTRY": "ARGENTINA"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 29,
        "COVER": "DONKEY KONG COUNTRY",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 29-37",
        "POSTER THEME": "MORTAL KOMBAT II / MAXIMUM CARNAGE",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 30,
        "COVER": "KILLER INSTINCT",
        "OWNED": "NO",
        "POSTER THEME": "AERO THE ACRO-BAT 2 / X-MEN MUTAN APOCALYPSE"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 31,
        "COVER": "FATAL FURY - CRESTA AMARILLA",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 31-34",
        "POSTER THEME": "FATAL FURY",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 32,
        "COVER": "SPIDER MAN",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 29-36",
        "POSTER THEME": "FX FIGHTER / SPIDER-MAN",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 33,
        "COVER": "MEGAMAN X2",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 34,
        "COVER": "CLAYFIGHTER 2",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 35,
        "COVER": "KILLER INSTINCT",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 36,
        "COVER": "POWER RANGERS",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 37,
        "COVER": "VIRTUAL BOY",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 38,
        "COVER": "YOSHI'S ISLAND - BEBÉ MARIO",
        "OWNED": "YES-POOR",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "PÁGINA CENTRAL SUELTA",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 39,
        "COVER": "MORTAL KOMBAT 3",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 40,
        "COVER": "DIDDY KONG'S QUEST",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 41,
        "COVER": "MARIO - NINTENDO 64 - ULTRA 64",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 42,
        "COVER": "SUPER MARIO RPG",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 43,
        "COVER": "DRAGON BALL",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 44,
        "COVER": "KILLER INSTINCT 2",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 45,
        "COVER": "TOY STORY",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 46,
        "COVER": "STREET FIGHTER ZERO 2",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 47,
        "COVER": "SUPER MARIO 64",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 48,
        "COVER": "KEN GRIIFEY JR'S WINNING RUN",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 49,
        "COVER": "NINTENDO 64 - PILOTWINGS 64",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 50,
        "COVER": "STAR WARS SHADOWS OF THE EMPIRE",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 51,
        "COVER": "MORTAL KOMBAT TRILOGY",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 52,
        "COVER": "KILLER INSTINCT GOLD",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 53,
        "COVER": "MARIO KART 64",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 54,
        "COVER": "TUROK",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 55,
        "COVER": "THE KING OF FIGHTERS 95",
        "OWNED": "NO",
        "POSTER THEME": "PILOTWINGS 64 / ULTIMATE MK3 - MK TRILOGY"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 56,
        "COVER": "MARIO - LUIGI - PEACH - BOWSER",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 57,
        "COVER": "BLAST CORPS",
        "OWNED": "NO",
        "POSTER THEME": "STREET FIGHTER ALPHA 2 / KIRBY STAR STACKER"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 58,
        "COVER": "STARFOX 64",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 59,
        "COVER": "CLAYFIGHTER 63 1/3",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 60,
        "COVER": "BANJO - KAZOOIE",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 61,
        "COVER": "GOLDENEYE 007",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 62,
        "COVER": "SAN FRANCISCO RUSH EXTREME RACING",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 63,
        "COVER": "DIDDY KONG RACING",
        "OWNED": "NO",
        "POSTER THEME": "GOLDENEYE 007 / MARIO KART 64"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 64,
        "COVER": "BOMBERMAN 64",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 65,
        "COVER": "ZELDA OCARINE",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 66,
        "COVER": "YOSHI'S STORY",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 67,
        "COVER": "NINJA GOEMON",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 68,
        "COVER": "1080 SNOWBOARDING",
        "OWNED": "YES-POOR",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "PÁGINAS 1-2 FALTA PEDAZO",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 69,
        "COVER": "WORLD CUP 98",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 70,
        "COVER": "BANJO - KAZOOIE",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 71,
        "COVER": "MORTAL KOMBAT 4",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 72,
        "COVER": "F-1 WORLD GRAND PRIX",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 73,
        "COVER": "POKEMON STAR PIKACHU - CRUIS'N WORLD",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 74,
        "COVER": "POKEMON - ASH - PIKACHU",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 75,
        "COVER": "ZELDA OCARINA",
        "OWNED": "NO",
        "POSTER THEME": "THE LEGEND OF ZELDA: OCARINA OF TIME"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 76,
        "COVER": "TUROK 2",
        "OWNED": "NO",
        "POSTER THEME": "YOSHI'S STORY"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 77,
        "COVER": "CASTLEVANIA",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 29-36",
        "POSTER THEME": "DEADLY ARTS / POKEMON",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 78,
        "COVER": "MARIO PARTY",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 79,
        "COVER": "NBA INTHE ZONE 99",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 80,
        "COVER": "SUPER SMASH BROTHERS",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 81,
        "COVER": "RAYMAN 2",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 82,
        "COVER": "STAR WARS RACER",
        "OWNED": "NO",
        "POSTER THEME": "STAR WARS RACER"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 83,
        "COVER": "SHADOW MAN",
        "OWNED": "NO",
        "POSTER THEME": "SHADOW MAN"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 84,
        "COVER": "POKEMON SNAP",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 29-36",
        "POSTER THEME": "POKEMON SNAP",
        "OBSERVATION": "-",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 85,
        "COVER": "HYBRID HEAVEN",
        "OWNED": "NO",
        "POSTER THEME": "HYBRID HEAVEN"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 86,
        "COVER": "JETFORCE GEMINI",
        "OWNED": "NO",
        "POSTER THEME": "JETFORCE GEMINI"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 87,
        "COVER": "STARCRAFT 64",
        "OWNED": "YES",
        "POSTER": "INCLUDED: PAGES 41-48",
        "POSTER THEME": "RE-VOLT",
        "OBSERVATION": "-",
        "COUNTRY": "CHILE"
    }
];

export default inventory_chilean;