const inventory = [
    {
        "YEAR EDIT": 1,
        "YEAR DATE": 1991,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 1,
        "COVER": "MARIO",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 1,
        "YEAR DATE": 1992,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 2,
        "COVER": "SUPER MARIO WORLD - YOSHI",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 1,
        "YEAR DATE": 1992,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 3,
        "COVER": "MARIO",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 1,
        "YEAR DATE": 1992,
        "MONTH": "MARCH",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 4,
        "COVER": "BART",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 1,
        "YEAR DATE": 1992,
        "MONTH": "APRIL",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 5,
        "COVER": "F-ZERO",
        "OWNED": "NO",
        "POSTER THEME": "DOUBLE DRAGON III"
    },
    {
        "YEAR EDIT": 1,
        "YEAR DATE": 1992,
        "MONTH": "MAY",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 6,
        "COVER": "TINY TOONS",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 1,
        "YEAR DATE": 1992,
        "MONTH": "JUNE",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 7,
        "COVER": "FLINTSTONES",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 1,
        "YEAR DATE": 1992,
        "MONTH": "JULY",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 8,
        "COVER": "STREET FIGHTER II",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 1,
        "YEAR DATE": 1992,
        "MONTH": "JULY",
        "YEAR NUMBER": "SPECIAL",
        "OVERALL NUMBER": "SPECIAL",
        "COVER": "CONTROLES SPECIAL",
        "OWNED": "NO",
        "POSTER THEME": "?"
    },
    {
        "YEAR EDIT": 1,
        "YEAR DATE": 1992,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 9,
        "COVER": "MEGA MAN 4",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 1,
        "YEAR DATE": 1992,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 10,
        "COVER": "BART VS. THE WORLD",
        "OWNED": "NO",
        "POSTER THEME": "ADVENTURE ISLAND 3"
    },
    {
        "YEAR EDIT": 1,
        "YEAR DATE": 1992,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 11,
        "COVER": "MARIO",
        "OWNED": "NO",
        "POSTER THEME": "FELIX THE CAT / AXELAY"
    },
    {
        "YEAR EDIT": 1,
        "YEAR DATE": 1992,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 12,
        "COVER": "COYOTE Y CORRECAMINOS",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 1,
        "YEAR DATE": 1992,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 13,
        "OVERALL NUMBER": 13,
        "COVER": "MICKEY MOUSE",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 14,
        "COVER": "BATMAN",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 15,
        "COVER": "TINY TOONS",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 16,
        "COVER": "SUPER FX",
        "OWNED": "NO",
        "POSTER THEME": "CALENDARIO STREET FIGHTER II / WIDGET"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 17,
        "COVER": "STARFOX",
        "OWNED": "NO",
        "POSTER THEME": "CYBERNATOR"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 18,
        "COVER": "BUBSY",
        "OWNED": "NO",
        "POSTER THEME": "Kid Dracula / Batman Returns / Star Fox / Publicidad Juegos"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 19,
        "COVER": "BATTLETOADS",
        "OWNED": "NO",
        "POSTER THEME": "BATTLETOADS / RUN SABER"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 20,
        "COVER": "STREET FIGHTER II TURBO",
        "OWNED": "NO",
        "POSTER THEME": "Calendario Street Fighter II  (Julio - Agosto) / Arte en Sobres"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "JULY",
        "YEAR NUMBER": "SPECIAL",
        "OVERALL NUMBER": "SPECIAL",
        "COVER": "STREET FIGHTER II SPECIAL",
        "OWNED": "NO",
        "POSTER THEME": "?"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 21,
        "COVER": "SUPER MARIO ALL STARS",
        "OWNED": "NO",
        "POSTER THEME": "Raging Figther / Arte en Sobres"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 22,
        "COVER": "MORTAL KOMBAT",
        "OWNED": "NO",
        "POSTER THEME": "Calendario Street Fighter II (Setiembre – Octubre) / Arte en sobres"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 23,
        "COVER": "JURASSIC PARK",
        "OWNED": "NO",
        "POSTER THEME": "Zombies Ate My Neighbors / Arte en Sobres"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 24,
        "COVER": "TEENAGE MUTANT NINJA TURTLES",
        "OWNED": "NO",
        "POSTER THEME": "Calendario Street Fighter II (Noviembre – Diciembre)  / Arte en Sobres"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 25,
        "COVER": "JULIO CESAR CHAVEZ",
        "OWNED": "NO",
        "POSTER THEME": "Volante del evento de presentación del videojuego de Chávez"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 26,
        "COVER": "MEGA MAN X",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 27,
        "COVER": "SUPER METROID",
        "OWNED": "NO",
        "POSTER THEME": "Megaman X / Arte en Sobres"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 28,
        "COVER": "NBA JAM",
        "OWNED": "NO",
        "POSTER THEME": "Lethal Enforces / Arte en Sobres"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 29,
        "COVER": "STREET FIGHTER II TURBO",
        "OWNED": "NO",
        "POSTER THEME": "Lista de Juegos de SNES / Arte en sobres"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 30,
        "COVER": "DONKEY KONG",
        "OWNED": "NO",
        "POSTER THEME": "King of Dragons / Arte en Sobres"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 31,
        "COVER": "STUNT RACE FX",
        "OWNED": "NO",
        "POSTER THEME": "SSF II Turbo / Arte sobre sobres"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 32,
        "COVER": "SUPER STREET FIGHTER II",
        "OWNED": "NO",
        "POSTER THEME": "Speedy Gonzales / Arte en sobres"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 33,
        "COVER": "BEAUTY AND THE BEAST",
        "OWNED": "NO",
        "POSTER THEME": "Aero the Acro-bat / Arte en sobres"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 34,
        "COVER": "MORTAL KOMBAT II",
        "OWNED": "NO",
        "POSTER THEME": "Darkstalkers / Arte en sobres"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 35,
        "COVER": "SUPER ADVENTURE ISLAND II",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 36,
        "COVER": "DONKEY KONG COUNTRY",
        "OWNED": "NO",
        "POSTER THEME": "Sparkster / Arte en Sobres"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 37,
        "COVER": "SAMURAI SHODOWN",
        "OWNED": "NO",
        "POSTER THEME": "Maximum Carnage / Arte en Sobres"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 38,
        "COVER": "MEGA MAN X",
        "OWNED": "NO",
        "POSTER THEME": "Zero The Kamikaze Squirrel + Aero the Acro-bat / Arte en  Sobres"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 39,
        "COVER": "KILLER INSTINCT",
        "OWNED": "NO",
        "POSTER THEME": "X-Men Mutant Apocalypse / Arte en sobres"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 40,
        "COVER": "KIRBY",
        "OWNED": "NO",
        "POSTER THEME": "FX Fighter / Arte Sobre Sobres"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 41,
        "COVER": "SPIDER MAN",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 42,
        "COVER": "STREET FIGHTER II",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 43,
        "COVER": "STREET FIGHTER II - NIGHT WARRIORS",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 44,
        "COVER": "VIRTUAL BOY",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 45,
        "COVER": "POWER RANGERS",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 46,
        "COVER": "KILLER INSTINCT",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 47,
        "COVER": "YOSHI'S ISLAND - BEBÉ MARIO",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 48,
        "COVER": "MORTAL KOMBAT 3",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 49,
        "COVER": "DIDDY KONG'S QUEST",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 50,
        "COVER": "MARIO - NINTENDO 64 - #50",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 51,
        "COVER": "SUPER MARIO RPG",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 52,
        "COVER": "DRAGON BALL",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 53,
        "COVER": "KILLER INSTINCT 2",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 54,
        "COVER": "TOY STORY",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 55,
        "COVER": "STREET FIGHTER ZERO 2",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 56,
        "COVER": "SUPER MARIO 64",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 57,
        "COVER": "KEN GRIIFEY JR'S WINNING RUN",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 58,
        "COVER": "NINTENDO 64",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 59,
        "COVER": "STAR WARS SHADOWS OF THE EMPIRE",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 60,
        "COVER": "MORTAL KOMBAT TRILOGY",
        "OWNED": "NO",
        "POSTER THEME": "Super Mario 64 / Arte en Sobres"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 61,
        "COVER": "KILLER INSTINCT GOLD",
        "OWNED": "NO",
        "POSTER THEME": "Street Fighter Alpha 2 / Arte en sobres"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 62,
        "COVER": "MARIO KART 64",
        "OWNED": "NO",
        "POSTER THEME": "Mortal Kombat Trilogy / Arte en Sobres"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 63,
        "COVER": "TUROK",
        "OWNED": "NO",
        "POSTER THEME": "Mario Kart 64 / Arte en sobres"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 64,
        "COVER": "THE KING OF FIGHTERS 95",
        "OWNED": "NO",
        "POSTER THEME": "Pilotwings 64 / Arte en sobres"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 65,
        "COVER": "MARIO - LUIGI - PEACH - BOWSER",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "APRIL",
        "YEAR NUMBER": "SPECIAL",
        "OVERALL NUMBER": "SPECIAL",
        "COVER": "MARIO - ARTE - SPECIAL",
        "OWNED": "NO",
        "POSTER THEME": "?"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 66,
        "COVER": "BLAST CORPS",
        "OWNED": "NO",
        "POSTER THEME": "Kirby’s Star Stacker / Arte en sobres"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 67,
        "COVER": "STARFOX 64",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 68,
        "COVER": "CLAYFIGHTER 63 1/3",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 69,
        "COVER": "BANJO - KAZOOIE",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 70,
        "COVER": "GOLDENEYE 007",
        "OWNED": "NO",
        "POSTER THEME": "Mortal Kombat Mytholgies / Arte en sobres"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 71,
        "COVER": "RUSH EXTREME RACING",
        "OWNED": "NO",
        "POSTER THEME": "Goldeneye 007 / Arte en sobres"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 72,
        "COVER": "DIDDY KONG RACING",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 73,
        "COVER": "BOMBERMAN 64",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 74,
        "COVER": "ZELDA OCARINE",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "SAN FRANCISO RUSH / ARTE SOBRES",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 75,
        "COVER": "YOSHI'S STORY",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 76,
        "COVER": "NINJA GOEMON",
        "OWNED": "NO",
        "POSTER THEME": "Yoshi’s Story / Arte en sobres"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 77,
        "COVER": "1080 SNOWBOARDING",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "APRIL",
        "YEAR NUMBER": "SPECIAL",
        "OVERALL NUMBER": "SPECIAL",
        "COVER": "ENCICLOPEDIA - CONSOLAS - SPECIAL",
        "OWNED": "NO",
        "POSTER THEME": "?"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 78,
        "COVER": "WORLD CUP 98",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 79,
        "COVER": "BANJO - KAZOOIE",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 80,
        "COVER": "F-ZERO X",
        "OWNED": "NO",
        "POSTER THEME": "Banjo Kazooie / Arte en Sobres"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 81,
        "COVER": "F-1 WORLD GRAND PRIX",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 82,
        "COVER": "NFL QUARTERBACK CLUB 99",
        "OWNED": "NO",
        "POSTER THEME": "Deadly Arts / Arte en sobres"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 83,
        "COVER": "POKEMON",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 84,
        "COVER": "TUROK 2",
        "OWNED": "NO",
        "POSTER THEME": "50 Pokémon / Arte en sobres"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 85,
        "COVER": "ZELDA",
        "OWNED": "NO",
        "POSTER THEME": "Yoshi’s Story (x2) "
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 86,
        "COVER": "CASTLEVANIA",
        "OWNED": "NO",
        "POSTER THEME": "Calendario TLOZ / Arte en sobres"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 87,
        "COVER": "MARIO PARTY",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 88,
        "COVER": "NBA JAM 99",
        "OWNED": "NO",
        "POSTER THEME": "Mario Party  / Arte en sobres"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 89,
        "COVER": "SUPER SMASH BROTHERS",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 90,
        "COVER": "RAYMAN 2",
        "OWNED": "NO",
        "POSTER THEME": "Calendario Super Smash Bros. / Arte en sobres"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 91,
        "COVER": "STAR WARS RACER",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 92,
        "COVER": "SHADOW MAN",
        "OWNED": "NO",
        "POSTER THEME": "Superman / Arte en sobres"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 93,
        "COVER": "POKEMON SNAP",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 94,
        "COVER": "HYBRID HEAVEN",
        "OWNED": "NO",
        "POSTER THEME": "Harrier 2001 / Arte en sobres"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 95,
        "COVER": "JETFORCE GEMINI",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 96,
        "COVER": "STARCRAFT 64",
        "OWNED": "YES-POOR",
        "POSTER": "INCLUDED",
        "POSTER THEME": "RE-VOLT",
        "OBSERVATION": "DAÑO EN EL LOMO - ALGUNAS PÁGINAS SUELTAS - PÁG. 87 RECORTADA"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 97,
        "COVER": "DONKEY KONG 64",
        "OWNED": "YES-POOR",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "PÁG. 7 RECORTADA"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": "SPECIAL",
        "OVERALL NUMBER": "SPECIAL",
        "COVER": "POKEMON - SPECIAL",
        "OWNED": "NO",
        "POSTER THEME": "?"
    },
    {
        "YEAR EDIT": 9,
        "YEAR DATE": 2000,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 98,
        "COVER": "MARIO PARTY 2",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "DONKEY KONG 64 / ARTE SOBRES",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 9,
        "YEAR DATE": 2000,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 99,
        "COVER": "RR64",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 9,
        "YEAR DATE": 2000,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 100,
        "COVER": "POKEMON STADIUM",
        "OWNED": "NO",
        "POSTER THEME": "100 PORTADAS / ARTE SOBRES"
    },
    {
        "YEAR EDIT": 9,
        "YEAR DATE": 2000,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 101,
        "COVER": "POKEMON TRADING CARD GAME",
        "OWNED": "YES-POOR",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "PÁGINA 68 RECORTADA"
    },
    {
        "YEAR EDIT": 9,
        "YEAR DATE": 2000,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 102,
        "COVER": "PERFECT DARK",
        "OWNED": "YES-POOR",
        "POSTER": "INCLUDED",
        "POSTER THEME": "POKEMON STADIUM (CALENDARIO MAYO-JUNIO) / ARTE SOBRES",
        "OBSERVATION": "PÁGINAS RECORTADAS: 21, 40, 53-54, 55-56, 57-58, 59-60, 79-80, 81-82. MISSING PAGES: 62-69"
    },
    {
        "YEAR EDIT": 9,
        "YEAR DATE": 2000,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 103,
        "COVER": "EXCITEBIKE 64",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 9,
        "YEAR DATE": 2000,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 104,
        "COVER": "KIRBY 64",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "PERFECT DARK / ARTE SOBRES",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 9,
        "YEAR DATE": 2000,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 105,
        "COVER": "TUROK 3",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 9,
        "YEAR DATE": 2000,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 106,
        "COVER": "MARIO TENNIS - PEACH - DAISY",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "BATMAN BEYOND / ARTE SOBRES",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 9,
        "YEAR DATE": 2000,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 107,
        "COVER": "POKEMON",
        "OWNED": "YES-POOR",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "PÁGINAS 37-38, 67-68 RECORTADAS"
    },
    {
        "YEAR EDIT": 9,
        "YEAR DATE": 2000,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 108,
        "COVER": "ZELDA MAJORA'S",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "THE LEGEND OF ZELDA: MAJORA'S MASK / ARTE SOBRES",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 9,
        "YEAR DATE": 2000,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 109,
        "COVER": "BANJO-TOOIE",
        "OWNED": "YES",
        "POSTER": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 10,
        "YEAR DATE": 2001,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 110,
        "COVER": "PAPER MARIO",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "TUROK 3 / ARTE SOBRES",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 10,
        "YEAR DATE": 2001,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 111,
        "COVER": "MEGA MAN 64",
        "OWNED": "YES-POOR",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "PÁGINAS RECORTADAS: 63-64"
    },
    {
        "YEAR EDIT": 10,
        "YEAR DATE": 2001,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 112,
        "COVER": "POKEMON STADIUM 2",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "PAPER MARIO / ARTE SOBRES",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 10,
        "YEAR DATE": 2001,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 113,
        "COVER": "KIRBY",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 10,
        "YEAR DATE": 2001,
        "MONTH": "APRIL",
        "YEAR NUMBER": "SPECIAL",
        "OVERALL NUMBER": "SPECIAL",
        "COVER": "POKEMON - SPECIAL",
        "OWNED": "NO",
        "POSTER THEME": "?"
    },
    {
        "YEAR EDIT": 10,
        "YEAR DATE": 2001,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 114,
        "COVER": "MARIO PARTY 3",
        "OWNED": "YES",
        "POSTER": "INCLUDED",
        "POSTER THEME": "CONKER'S BAD FUR DAY / ARTE SOBRES",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 10,
        "YEAR DATE": 2001,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 115,
        "COVER": "GAMEBOY ADVANCE",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 10,
        "YEAR DATE": 2001,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 116,
        "COVER": "CASTLEVANIA",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "THE LEGEND OF ZELDA: ORACLE OF AGES-SEASONS / ARTE SOBRES",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 10,
        "YEAR DATE": 2001,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 117,
        "COVER": "MARIO KART SUPER CIRCUIT",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 10,
        "YEAR DATE": 2001,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 118,
        "COVER": "SUPER STREET FIGHTER II",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "SUPER STREET FIGHTER II / ARTE SOBRES",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 10,
        "YEAR DATE": 2001,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 119,
        "COVER": "GAMECUBE",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 10,
        "YEAR DATE": 2001,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 120,
        "COVER": "LUIGI'S MANSION",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "GAMECUBE / ARTE SOBRES",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 10,
        "YEAR DATE": 2001,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 121,
        "COVER": "10 AÑOS - SUPER SMAH BROS. MELEE",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 11,
        "YEAR DATE": 2002,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 122,
        "COVER": "ETERNAL DARKNESS",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "ETERNAL DARKNESS / ARTE SOBRES",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 11,
        "YEAR DATE": 2002,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 123,
        "COVER": "NBA COURTSIDE2002 - KOBE",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 11,
        "YEAR DATE": 2002,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 124,
        "COVER": "SUPER MARIO WORLD - YOSHI - SUPER MARIO ADVANCE 2",
        "OWNED": "YES-POOR",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "MEGAMAN BATTLER NETWORK 2 / ARTE SOBRES",
        "OBSERVATION": "PÁGINAS RECORTADAS: 9-10, 95-96"
    },
    {
        "YEAR EDIT": 11,
        "YEAR DATE": 2002,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 125,
        "COVER": "SONIC ADVENTURE 2 BATTLE",
        "OWNED": "YES-POOR",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "PÁGINA 94 MEDIO SUELTA"
    },
    {
        "YEAR EDIT": 11,
        "YEAR DATE": 2002,
        "MONTH": "APRIL",
        "YEAR NUMBER": "SPECIAL",
        "OVERALL NUMBER": "SPECIAL",
        "COVER": "ZELDA - SPECIAL",
        "OWNED": "NO",
        "POSTER THEME": "?"
    },
    {
        "YEAR EDIT": 11,
        "YEAR DATE": 2002,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 126,
        "COVER": "RESIDENT EVIL",
        "OWNED": "YES",
        "POSTER": "INCLUDED",
        "POSTER THEME": "SONIC ADVENTURE 2 BATTLE / ARTE SOBRES",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 11,
        "YEAR DATE": 2002,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 127,
        "COVER": "2002 FIFA WORLD CUP",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 11,
        "YEAR DATE": 2002,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 128,
        "COVER": "E3 - SUPER MARIO SUNSHINE - ZELDA - METROID - STARFOX",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 11,
        "YEAR DATE": 2002,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 129,
        "COVER": "SUPER MARIO SUNSHINE",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 11,
        "YEAR DATE": 2002,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 130,
        "COVER": "STARFOX ADVENTURES",
        "OWNED": "YES",
        "POSTER": "INCLUDED",
        "POSTER THEME": "MEGAMAN BATTLER NETWORK 2 / ARTE SOBRES",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 11,
        "YEAR DATE": 2002,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 131,
        "COVER": "MARIO PARTY 4",
        "OWNED": "YES-POOR",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "DAÑO EN EL LOMO - PORTADA UN POCO SUELTA"
    },
    {
        "YEAR EDIT": 11,
        "YEAR DATE": 2002,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 132,
        "COVER": "METROID PRIME",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "MARIO PARY 4 / ARTE SOBRES",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 11,
        "YEAR DATE": 2002,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 133,
        "COVER": "ZELDA",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 12,
        "YEAR DATE": 2003,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 134,
        "COVER": "POKEMON",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 12,
        "YEAR DATE": 2003,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 135,
        "COVER": "ZELDA",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 12,
        "YEAR DATE": 2003,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 136,
        "COVER": "POKEMON",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "KIRBY NIGHTMARE IN DREAM LAND / ARTE SOBRES",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 12,
        "YEAR DATE": 2003,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 137,
        "COVER": "GOLDEN SUN",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 12,
        "YEAR DATE": 2003,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 138,
        "COVER": "WARIO WORLD",
        "OWNED": "YES",
        "POSTER": "INCLUDED",
        "POSTER THEME": "THE LEGEND OF ZELDA: THE WIND WAKER / ARTE SOBRES",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 12,
        "YEAR DATE": 2003,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 139,
        "COVER": "ADVANCE WARS 2",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 12,
        "YEAR DATE": 2003,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 140,
        "COVER": "F-ZERO GX",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 12,
        "YEAR DATE": 2003,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 141,
        "COVER": "ZELDA - SOUL CALIBUR II",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 12,
        "YEAR DATE": 2003,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 142,
        "COVER": "VIEWTIFUL JOE",
        "OWNED": "YES",
        "POSTER": "INCLUDED",
        "POSTER THEME": "SOUL CALIBUR II / ARTE SOBRES",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 12,
        "YEAR DATE": 2003,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 143,
        "COVER": "STAR WARS",
        "OWNED": "YES",
        "POSTER": "INCLUDED",
        "POSTER THEME": "VIEWTIFUL JOE / P.N.03",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 12,
        "YEAR DATE": 2003,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": "SPECIAL",
        "OVERALL NUMBER": "SPECIAL",
        "COVER": "NINTENDO - GAMECUBE - SPECIAL",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "?",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 12,
        "YEAR DATE": 2003,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 144,
        "COVER": "MARIO KART DOUBLE DASH",
        "OWNED": "YES",
        "POSTER": "INCLUDED",
        "POSTER THEME": "FINAL FANTASY TACTICS ADVANCE / MARIO KART DOUBLE DASH",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 12,
        "YEAR DATE": 2003,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 145,
        "COVER": "MARIO & LUIGI",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 13,
        "YEAR DATE": 2004,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 146,
        "COVER": "FINAL FANTASY",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "FIRE EMBLEM / SOUL OF MANA",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 13,
        "YEAR DATE": 2004,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 147,
        "COVER": "METAL GEAR SOLID",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 13,
        "YEAR DATE": 2004,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 148,
        "COVER": "POKEMON COLLOSEUM",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "FINAL FANTASY CRYSTAL CHRONICLES / METAL GEAR SOLID THE TWIN SNAKES",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 13,
        "YEAR DATE": 2004,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 149,
        "COVER": "BOMBERMAN JETTERS",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 13,
        "YEAR DATE": 2004,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 150,
        "COVER": "HARRY POTTER AZKABAN",
        "OWNED": "YES",
        "POSTER": "INCLUDED",
        "POSTER THEME": "THE LORD OF THE RINGS: THE RETURN OF THE KING",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 13,
        "YEAR DATE": 2004,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 151,
        "COVER": "TALES OF SIMPHONIA",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 13,
        "YEAR DATE": 2004,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 152,
        "COVER": "E3 - ZELDA",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 13,
        "YEAR DATE": 2004,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 153,
        "COVER": "DONKEY KONGA",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 13,
        "YEAR DATE": 2004,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 154,
        "COVER": "SRS - STREET RACING SYNDICATE",
        "OWNED": "YES",
        "POSTER": "INCLUDED",
        "POSTER THEME": "KIRBY & THE AMAZING MIRROR / SRS",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 13,
        "YEAR DATE": 2004,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 155,
        "COVER": "METROID PRIME 2 ECHOES",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 13,
        "YEAR DATE": 2004,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": "SPECIAL",
        "OVERALL NUMBER": "SPECIAL",
        "COVER": "METROID PRIME 2 ECHOES - SPECIAL",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "?",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 13,
        "YEAR DATE": 2004,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 156,
        "COVER": "PRINCE OF PERSIA",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 33-48",
        "POSTER THEME": "PRINCE OF PERSIA WARRIOR WITHIN",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 13,
        "YEAR DATE": 2004,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 157,
        "COVER": "NINTENDO DS - ANIVERSARIO XIII",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 14,
        "YEAR DATE": 2005,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 158,
        "COVER": "RESIDENT EVIL 4",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 73-88",
        "POSTER THEME": "RESIDENT EVIL 4",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 14,
        "YEAR DATE": 2005,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 159,
        "COVER": "MORTAL KOMBAT DECEPTION",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 14,
        "YEAR DATE": 2005,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 160,
        "COVER": "SPLINTER CELL",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "SPLINTER CELL / THE LEGEND OF ZELDA: THE MINISH CAP",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 14,
        "YEAR DATE": 2005,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 161,
        "COVER": "GAMECUBE - NINTENDO DS - GAMEBOY ADVANCE - REVOLUTION",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 14,
        "YEAR DATE": 2005,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 162,
        "COVER": "STAR WARS EPISODE III",
        "OWNED": "YES",
        "POSTER": "INCLUDED",
        "POSTER THEME": "POKEMON EMERALD VERSION / ARTE SOBRES",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 14,
        "YEAR DATE": 2005,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 163,
        "COVER": "KILLER 7",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 14,
        "YEAR DATE": 2005,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 164,
        "COVER": "E3 - ZELDA - MIYAMOTO",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 14,
        "YEAR DATE": 2005,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 165,
        "COVER": "GEIST",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "GEIST / YOSHI TOPSY-TURVY",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 14,
        "YEAR DATE": 2005,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 166,
        "COVER": "MARIO SUPERSTAR BASEBALL",
        "OWNED": "YES",
        "POSTER": "INCLUDED",
        "POSTER THEME": "MEGAMAN BATTLER NETWORK 5 / ARTE SOBRES",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 14,
        "YEAR DATE": 2005,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 167,
        "COVER": "MARIO KART DS",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 14,
        "YEAR DATE": 2005,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 168,
        "COVER": "SUPER MARIO STRIKERS",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "RAINBOW SIX / CASTLEVANIA: DAWN OF SORROW",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 14,
        "YEAR DATE": 2005,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 169,
        "COVER": "PRINCE OF PERSIA",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 73-88",
        "POSTER THEME": "MARIO STRIKERS",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 15,
        "YEAR DATE": 2006,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 170,
        "COVER": "ESTRELLAS DEL 2006 - MARIO - LUIGI - KIRBY - METROID - PEACH - ZELDA",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 15,
        "YEAR DATE": 2006,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 171,
        "COVER": "SUPER PRINCESS PEACH",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "X-MEN LEGENDS II / PRINCE OF PERSIA THE TWO THRONES",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 15,
        "YEAR DATE": 2006,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 172,
        "COVER": "METROID PRIME HUNTERS",
        "OWNED": "YES",
        "POSTER": "INCLUDED",
        "POSTER THEME": "METROID PRIME HUNTERS / CHIBI-ROBO",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 15,
        "YEAR DATE": 2006,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 173,
        "COVER": "NARUTO CLASH OF NINJA",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 15,
        "YEAR DATE": 2006,
        "MONTH": "APRIL",
        "YEAR NUMBER": "SPECIAL",
        "OVERALL NUMBER": "SPECIAL",
        "COVER": "RESIDENT EVIL - SPECIAL",
        "OWNED": "NO",
        "POSTER THEME": "?",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 15,
        "YEAR DATE": 2006,
        "MONTH": "APRIL",
        "YEAR NUMBER": "SPECIAL2",
        "OVERALL NUMBER": "SPECIAL2",
        "COVER": "RESIDENT EVIL - SPECIAL",
        "OWNED": "NO",
        "POSTER THEME": "?",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 15,
        "YEAR DATE": 2006,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 174,
        "COVER": "NEW SUPER MARIO BROS.",
        "OWNED": "YES",
        "POSTER": "INCLUDED",
        "POSTER THEME": "MARIO Y LUIGI",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 15,
        "YEAR DATE": 2006,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 175,
        "COVER": "WII",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 15,
        "YEAR DATE": 2006,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 176,
        "COVER": "E3 - REDSTEEL",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 15,
        "YEAR DATE": 2006,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 177,
        "COVER": "STARFOX COMMAND",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "SUPER MONKEY BALL ADVENTURE / CASTLEVANIA PORTRAIT OF RUIN",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 15,
        "YEAR DATE": 2006,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 178,
        "COVER": "MARIO VS. DONKEY KONG 2",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 15,
        "YEAR DATE": 2006,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 179,
        "COVER": "FIFA 07",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 15,
        "YEAR DATE": 2006,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 180,
        "COVER": "ZELDA",
        "OWNED": "YES",
        "POSTER": "INCLUDED",
        "POSTER THEME": "THE LEGEND OF ZELDA TWILIGHT PRINCESS",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 15,
        "YEAR DATE": 2006,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 181,
        "COVER": "XV AÑOS",
        "OWNED": "YES",
        "POSTER": "MISSING: PAGES 57-64",
        "POSTER THEME": "REDSTEEL / MARVEL ULTIMATE ALLIANCE",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 16,
        "YEAR DATE": 2007,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 182,
        "COVER": "WARIOWARE SMOOTH MOVES",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 16,
        "YEAR DATE": 2007,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 183,
        "COVER": "DIDDY KONG RACING DS",
        "OWNED": "YES",
        "POSTER": "INCLUDED",
        "POSTER THEME": "DIDDY KONG RAACING DS / THE LEGEND OF ZELDA TWILIGHT PRINCESS",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 16,
        "YEAR DATE": 2007,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 184,
        "COVER": "PRINCE OF PERSIA",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 16,
        "YEAR DATE": 2007,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 185,
        "COVER": "TMNT - TEENAGE MUTANT NINJA TURTLES",
        "OWNED": "YES",
        "POSTER": "INCLUDED",
        "POSTER THEME": "PRINCE OF PERSIA RIVAL SWORDS / LUNAR KNIGHTS",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 16,
        "YEAR DATE": 2007,
        "MONTH": "APRIL",
        "YEAR NUMBER": "SPECIAL",
        "OVERALL NUMBER": "SPECIAL",
        "COVER": "ARTE EN LOS JUEGOS DE MARIO - SPECIAL",
        "OWNED": "NO",
        "POSTER THEME": "?",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 16,
        "YEAR DATE": 2007,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 186,
        "COVER": "SPIDER MAN 3",
        "OWNED": "YES",
        "POSTER": "INCLUDED",
        "POSTER THEME": "TMNT / SPIDER-MAN 3 THE GAME",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 16,
        "YEAR DATE": 2007,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 187,
        "COVER": "HARRY POTTER PHOENIX",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 16,
        "YEAR DATE": 2007,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 188,
        "COVER": "MARIO STRIKERS CHARGED",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 16,
        "YEAR DATE": 2007,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 189,
        "COVER": "METROID PRIME 3 CORRUPTION",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 16,
        "YEAR DATE": 2007,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 190,
        "COVER": "ZELDA",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 16,
        "YEAR DATE": 2007,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 191,
        "COVER": "FIFA 08",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 16,
        "YEAR DATE": 2007,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 192,
        "COVER": "SUPER MARIO GALAXY",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 16,
        "YEAR DATE": 2007,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 193,
        "COVER": "MARIO PARTY DS",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 17,
        "YEAR DATE": 2008,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 194,
        "COVER": "2008 - MARIO KART WII",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 17,
        "YEAR DATE": 2008,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 195,
        "COVER": "SUPER SMASH BROS. BRAWL",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 17,
        "YEAR DATE": 2008,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 196,
        "COVER": "NO MORE HEROES",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 17,
        "YEAR DATE": 2008,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 197,
        "COVER": "OKAMI",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 17,
        "YEAR DATE": 2008,
        "MONTH": "APRIL",
        "YEAR NUMBER": "SPECIAL",
        "OVERALL NUMBER": "SPECIAL",
        "COVER": "SUPER SMASH BROS. - SPECIAL",
        "OWNED": "NO",
        "POSTER THEME": "?",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 17,
        "YEAR DATE": 2008,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 198,
        "COVER": "MARIO KART WII",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 17,
        "YEAR DATE": 2008,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 199,
        "COVER": "GUITAR HERO",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 17,
        "YEAR DATE": 2008,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 200,
        "COVER": 200,
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 17,
        "YEAR DATE": 2008,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 201,
        "COVER": "FINAL FANTASY IV",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 17,
        "YEAR DATE": 2008,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 202,
        "COVER": "E3 - WARIO",
        "OWNED": "YES-POOR",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "FROM COVER TO PAGE 20 WITH A LITTLE DETAIL IN THE LOWER LEFT CORNER"
    },
    {
        "YEAR EDIT": 17,
        "YEAR DATE": 2008,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 203,
        "COVER": "HARRY POTTER",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 17,
        "YEAR DATE": 2008,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 204,
        "COVER": "RAYMAN RAVING RABBIDS",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 17,
        "YEAR DATE": 2008,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 205,
        "COVER": "ANIMAL CROSSING",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 18,
        "YEAR DATE": 2009,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 206,
        "COVER": "PRINCE OF PERSIA",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 18,
        "YEAR DATE": 2009,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 207,
        "COVER": "MEGA MAN",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 18,
        "YEAR DATE": 2009,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 208,
        "COVER": "DEADRISING - ZOMBIS",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 18,
        "YEAR DATE": 2009,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 209,
        "COVER": "POKEMON PLATINUM",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 18,
        "YEAR DATE": 2009,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 210,
        "COVER": "PUNCH OUT WII",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 18,
        "YEAR DATE": 2009,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 211,
        "COVER": "NEED FOR SPEED NITRO",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 18,
        "YEAR DATE": 2009,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 212,
        "COVER": "E3 - ZELDA",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 18,
        "YEAR DATE": 2009,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 213,
        "COVER": "MARIO - YOSHI - MÁS DE 60",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 18,
        "YEAR DATE": 2009,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 214,
        "COVER": "METROID PRIME TRILOGY",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 18,
        "YEAR DATE": 2009,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 215,
        "COVER": "PES 2010 - MESSI",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 18,
        "YEAR DATE": 2009,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 216,
        "COVER": "TATSUNOKO VS. CAPCOM - RYU - CHUN LI",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 18,
        "YEAR DATE": 2009,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 217,
        "COVER": "TENEMOS ESTRELLA - MARIO",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 19,
        "YEAR DATE": 2010,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 218,
        "COVER": "ZELDA - TREN",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 19,
        "YEAR DATE": 2010,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 219,
        "COVER": "NO MORE HEROES 2",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 19,
        "YEAR DATE": 2010,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 220,
        "COVER": "SONIC",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 19,
        "YEAR DATE": 2010,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 221,
        "COVER": "WARIOWARE D.I.Y.",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 19,
        "YEAR DATE": 2010,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 222,
        "COVER": "SUPER MARIO GALAXY 2 - YOSHI",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 19,
        "YEAR DATE": 2010,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 223,
        "COVER": "IRON MAN 2",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 19,
        "YEAR DATE": 2010,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 224,
        "COVER": "E3 - MARIO - LUIGI - BASKETBALL",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 19,
        "YEAR DATE": 2010,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 225,
        "COVER": "ZELDA",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 19,
        "YEAR DATE": 2010,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 226,
        "COVER": "METROID OTHER M",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 19,
        "YEAR DATE": 2010,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 227,
        "COVER": "NBA JAM",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 19,
        "YEAR DATE": 2010,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 228,
        "COVER": "PES 2011 - MESSI",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 19,
        "YEAR DATE": 2010,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 229,
        "COVER": "DONKEY KONG COUNTRY RETURNS",
        "OWNED": "YES-POOR",
        "POSTER": "MISSING: CHILEAN VERSION",
        "POSTER THEME": "METROID OTHER M / DONKEY KONG COUNTRY RETURN",
        "OBSERVATION": "DAÑO EN EL LOMO - FROM CHILE"
    },
    {
        "YEAR EDIT": 20,
        "YEAR DATE": 2011,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 230,
        "COVER": "25TH ANNIVERSARY - SUPER MARIO ALL STARS",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "FROM CHILE"
    },
    {
        "YEAR EDIT": 20,
        "YEAR DATE": 2011,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 231,
        "COVER": "CONDUIT 2",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 20,
        "YEAR DATE": 2011,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 232,
        "COVER": "KID ICARUS - NINTENDO 3DS",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 20,
        "YEAR DATE": 2011,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 233,
        "COVER": "SUPER STREET FIGHTER IV 3D EDITION",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "FROM CHILE"
    },
    {
        "YEAR EDIT": 20,
        "YEAR DATE": 2011,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 234,
        "COVER": "SONIC",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 20,
        "YEAR DATE": 2011,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 235,
        "COVER": "ZELDA",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 20,
        "YEAR DATE": 2011,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 236,
        "COVER": "E3 - MARIO - WII U",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 20,
        "YEAR DATE": 2011,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 237,
        "COVER": "METAL GEAR SOLID 3D",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "FROM CHILE"
    },
    {
        "YEAR EDIT": 20,
        "YEAR DATE": 2011,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 238,
        "COVER": "STARFOX 64 3D",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 20,
        "YEAR DATE": 2011,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 239,
        "COVER": "FIFA 12 - ROONEY - MARQUEZ",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "FROM CHILE"
    },
    {
        "YEAR EDIT": 20,
        "YEAR DATE": 2011,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 240,
        "COVER": "MARIO & SONIC AT THE LONDON 2012 OLYMPIC GAMES",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 20,
        "YEAR DATE": 2011,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 241,
        "COVER": "ZELDA",
        "OWNED": "NO",
        "POSTER THEME": "THE LEGEND OF ZELDA: SKYWARD SWORD"
    },
    {
        "YEAR EDIT": 21,
        "YEAR DATE": 2012,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 242,
        "COVER": "SUPER MARIO 3D LAND",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 21,
        "YEAR DATE": 2012,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 243,
        "COVER": "TEKKEN 3D PRIME EDITION",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 21,
        "YEAR DATE": 2012,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 244,
        "COVER": "KID ICARUS",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 21,
        "YEAR DATE": 2012,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 245,
        "COVER": "BEBÉ MARIO - POKEPARK 2",
        "OWNED": "YES",
        "POSTER": "MISSING: CHILEAN VERSION",
        "POSTER THEME": "MARIO KART 7 / POKEPARK 2",
        "OBSERVATION": "FROM CHILE"
    },
    {
        "YEAR EDIT": 21,
        "YEAR DATE": 2012,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 246,
        "COVER": "EPIC MICKEY 2",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 21,
        "YEAR DATE": 2012,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 247,
        "COVER": "MARIO TENNIS OPEN",
        "OWNED": "YES-POOR",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "PORTADA DAÑADA EN ESQUINA SUPERIOR DERECHA. CONTRAPORTADA CON TROZO FALTANTE"
    },
    {
        "YEAR EDIT": 21,
        "YEAR DATE": 2012,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 248,
        "COVER": "NEW SUPER MARIO BROS. U",
        "OWNED": "YES-POOR",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "MISSING PAGES: 20-21"
    },
    {
        "YEAR EDIT": 21,
        "YEAR DATE": 2012,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 249,
        "COVER": "RAYMAN",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 21,
        "YEAR DATE": 2012,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 250,
        "COVER": "METROID",
        "OWNED": "NO",
        "POSTER THEME": "METROID"
    },
    {
        "YEAR EDIT": 21,
        "YEAR DATE": 2012,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 251,
        "COVER": "KIRBY 20TH ANNIVERSARY - CELEBREMOS",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 21,
        "YEAR DATE": 2012,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 252,
        "COVER": "NINTENDO LAND - WII U",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 21,
        "YEAR DATE": 2012,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 253,
        "COVER": "21 ANIVERSARIO - MARIO - YOSHI",
        "OWNED": "NO",
        "POSTER THEME": "NEW SUPER MARIO BROS. U / BATMAN ARKHAM CITY"
    },
    {
        "YEAR EDIT": 22,
        "YEAR DATE": 2013,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 254,
        "COVER": "NINJA GAIDEN 3",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 22,
        "YEAR DATE": 2013,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 255,
        "COVER": "LUIGI'S MANSION",
        "OWNED": "YES",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-"
    },
    {
        "YEAR EDIT": 22,
        "YEAR DATE": 2013,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 256,
        "COVER": "CASTLEVANIA",
        "OWNED": "NO",
        "POSTER THEME": "CASTLEVANIA: LORD OF SHADOW / LUIGI'S MANSION DARK MOON"
    },
    {
        "YEAR EDIT": 22,
        "YEAR DATE": 2013,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 257,
        "COVER": "INJUSTICE",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 22,
        "YEAR DATE": 2013,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 258,
        "COVER": "DONKEY KONG",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 22,
        "YEAR DATE": 2013,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 259,
        "COVER": "ANIMAL CROSSING",
        "OWNED": "NO",
        "POSTER THEME": "CALENDARIOS DE ANIMAL CROSSING (JUN 2013 - MAY 2014)"
    },
    {
        "YEAR EDIT": 22,
        "YEAR DATE": 2013,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 260,
        "COVER": "DISNEY INFINITY",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 22,
        "YEAR DATE": 2013,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 261,
        "COVER": "SUPER SMASH BROS.",
        "OWNED": "YES",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 22,
        "YEAR DATE": 2013,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 262,
        "COVER": "PIKMIN 3",
        "OWNED": "YES",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 22,
        "YEAR DATE": 2013,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 263,
        "COVER": "ZELDA WINDWAKER HD",
        "OWNED": "YES",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 22,
        "YEAR DATE": 2013,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 264,
        "COVER": "SONIC LOST WORLD",
        "OWNED": "YES",
        "POSTER THEME": "SUPER SMASH BROS. / NEW SUPER LUIGI U"
    },
    {
        "YEAR EDIT": 22,
        "YEAR DATE": 2013,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 265,
        "COVER": "SUPER MARIO 3D WORLD",
        "OWNED": "YES",
        "POSTER THEME": "SUPER MARIO 3D WORLD / THE LEGEND OF ZELDA: A LINK BETWEEN WORLDS"
    },
    {
        "YEAR EDIT": 23,
        "YEAR DATE": 2014,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 266,
        "COVER": "MARIO PARTY ISLAND TOUR",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 23,
        "YEAR DATE": 2014,
        "MONTH": "FEBRUARY",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 267,
        "COVER": "ZELDA - PAREJAS LEGENDARIAS",
        "OWNED": "YES",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 23,
        "YEAR DATE": 2014,
        "MONTH": "MARCH",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 268,
        "COVER": "DONKEY KONG COUNTRY TROPICAL FREEZE",
        "OWNED": "YES",
        "POSTER THEME": "DONKEY KONG COUNTRY TROPICAL FREEZE / MARIO PARTY ISLAND TOUR"
    },
    {
        "YEAR EDIT": 23,
        "YEAR DATE": 2014,
        "MONTH": "APRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 269,
        "COVER": "YOSHI'S NEW ISLAND - BEBÉ MARIO",
        "OWNED": "YES",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 23,
        "YEAR DATE": 2014,
        "MONTH": "APRIL",
        "YEAR NUMBER": "SPECIAL",
        "OVERALL NUMBER": "SPECIAL",
        "COVER": "EL MUNDO DE SUPER MARIO - SPECIAL",
        "OWNED": "YES",
        "POSTER THEME": "?"
    },
    {
        "YEAR EDIT": 23,
        "YEAR DATE": 2014,
        "MONTH": "MAY",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 270,
        "COVER": "MARIO KART 8",
        "OWNED": "YES",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 23,
        "YEAR DATE": 2014,
        "MONTH": "JUNE",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 271,
        "COVER": "KIRBY TRIPLE DELUXE",
        "OWNED": "YES",
        "POSTER THEME": "MARIO KART 8 / YOSHI'S NEW ISLAND"
    },
    {
        "YEAR EDIT": 23,
        "YEAR DATE": 2014,
        "MONTH": "JULY",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 272,
        "COVER": "SUPER SMASH BROS. FOR NINTENDO 3DS",
        "OWNED": "YES",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 23,
        "YEAR DATE": 2014,
        "MONTH": "AUGUST",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 273,
        "COVER": "DISNEY INFINITY 2.0 - SPIDER MAN",
        "OWNED": "YES",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 23,
        "YEAR DATE": 2014,
        "MONTH": "SEPTEMBER",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 274,
        "COVER": "ZELDA - HYRULE WARRIORS",
        "OWNED": "YES",
        "POSTER THEME": "MARIO GOLF WORLD TOUR"
    },
    {
        "YEAR EDIT": 23,
        "YEAR DATE": 2014,
        "MONTH": "OCTOBER",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 275,
        "COVER": "BAYONETTA 2",
        "OWNED": "YES",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 23,
        "YEAR DATE": 2014,
        "MONTH": "NOVEMBER",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 276,
        "COVER": "EL MUNDO DE BOWSER - SPECIAL",
        "OWNED": "YES",
        "POSTER THEME": "MARIO PARTY 10 / MARIO & LUIGI BOWSER'S INSIDE STORY"
    },
    {
        "YEAR EDIT": 23,
        "YEAR DATE": 2014,
        "MONTH": "DECEMBER",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 277,
        "COVER": "SUPER SMASH BROS. FOR WII U",
        "OWNED": "YES",
        "POSTER THEME": "BAYONETTA 2 / SUPER SMASH BROS. FOR WII U"
    },
    {
        "YEAR EDIT": 24,
        "YEAR DATE": 2015,
        "MONTH": "JANUARY",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 278,
        "COVER": "LA JUNGLA DE DONKEY KONG - SPECIAL",
        "OWNED": "YES",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 24,
        "YEAR DATE": 2015,
        "MONTH": "MARCH",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 279,
        "COVER": "ZELDA MAJORA'S MASK",
        "OWNED": "YES",
        "POSTER THEME": "THE LEGEND OF ZELDA: MAJORA'S MASK 3D"
    },
    {
        "YEAR EDIT": 24,
        "YEAR DATE": 2015,
        "MONTH": "MAY",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 280,
        "COVER": "MARIO PARTY 10",
        "OWNED": "YES",
        "POSTER THEME": "MARIO PARTY 10"
    },
    {
        "YEAR EDIT": 24,
        "YEAR DATE": 2015,
        "MONTH": "JULY",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 281,
        "COVER": "SUPER MARIO MAKER",
        "OWNED": "YES",
        "POSTER THEME": "SUPER MARIO MAKER / SPLATOON"
    }
];

export default inventory;